// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv_3uEAZgtf7-hUySkRtNRc1d1goFhBvk',
    appId: '1:722260502638:web:82df42d80f84704838de7f',
    messagingSenderId: '722260502638',
    projectId: 'mycamerafilter',
    authDomain: 'mycamerafilter.firebaseapp.com',
    storageBucket: 'mycamerafilter.appspot.com',
    measurementId: 'G-XVJ92ESTHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIUE2mCKd_t90DAo0fsbx2vnChr8vV5nc',
    appId: '1:722260502638:android:5fade66d6530050438de7f',
    messagingSenderId: '722260502638',
    projectId: 'mycamerafilter',
    storageBucket: 'mycamerafilter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkOBVsANgfF6W0lhFFgdSNFkFiWnDKkvs',
    appId: '1:722260502638:ios:5981fc44242e58b638de7f',
    messagingSenderId: '722260502638',
    projectId: 'mycamerafilter',
    storageBucket: 'mycamerafilter.appspot.com',
    iosBundleId: 'com.example.mycamerafilter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkOBVsANgfF6W0lhFFgdSNFkFiWnDKkvs',
    appId: '1:722260502638:ios:edc8651dea27b26f38de7f',
    messagingSenderId: '722260502638',
    projectId: 'mycamerafilter',
    storageBucket: 'mycamerafilter.appspot.com',
    iosBundleId: 'com.example.mycamerafilter.RunnerTests',
  );
}
